"""Create LaTeX matrix code from transfer-function coefficient JSON.

Reads transfer_function_coefficients.json (true + estimated entries),
rounds all coefficients to the requested decimals (default 4), and saves
LaTeX code for both matrices to a .tex file in the same directory as JSON.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


# ------------------------------------------------------------------
# Optional override: set this to the full path of transfer_function_coefficients.json
# Example:
# coeff_data_loc = "/path/to/transfer_function/transfer_function_coefficients.json"
# ------------------------------------------------------------------
coeff_data_loc = "/Users/home/Documents/naz/research_codes/counterfactual_reasoning/synthetic_exp/norm_comp_2/Components_2/rebuttal/main1/mc_002/transfer_function/transfer_function_coefficients.json"


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert transfer-function coefficient JSON to LaTeX matrix code."
    )
    parser.add_argument(
        "--coeff-json",
        type=Path,
        default=None,
        help="Path to transfer_function_coefficients.json.",
    )
    parser.add_argument(
        "--output-tex",
        type=Path,
        default=None,
        help=(
            "Path to output .tex file. Default: "
            "<coeff_json_dir>/transfer_function_matrix_latex.tex"
        ),
    )
    parser.add_argument(
        "--decimals",
        type=int,
        default=4,
        help="Decimal places for rounding coefficients (default: 4).",
    )
    return parser.parse_args()


def _resolve_coeff_json(args: argparse.Namespace) -> Path:
    if coeff_data_loc:
        path = Path(coeff_data_loc).expanduser()
    elif args.coeff_json is not None:
        path = args.coeff_json.expanduser()
    else:
        raise ValueError(
            "No coefficient JSON path provided. Set coeff_data_loc in this file "
            "or pass --coeff-json /path/to/transfer_function_coefficients.json."
        )

    if not path.exists():
        raise FileNotFoundError(f"Coefficient JSON file not found: {path}")
    return path


def _format_number(value: float, decimals: int) -> str:
    rounded = round(float(value), int(decimals))
    if abs(rounded) < 10.0 ** (-int(decimals)):
        rounded = 0.0
    return f"{rounded:.{int(decimals)}f}"


def _poly_to_latex(coeffs: list[float], var: str, decimals: int) -> str:
    degree = len(coeffs) - 1
    terms: list[tuple[str, str]] = []

    for idx, coeff in enumerate(coeffs):
        rounded = round(float(coeff), int(decimals))
        if abs(rounded) < 10.0 ** (-int(decimals)):
            continue

        power = degree - idx
        mag = _format_number(abs(rounded), decimals)

        if power == 0:
            body = mag
        elif power == 1:
            body = f"{mag}{var}"
        else:
            body = f"{mag}{var}^{{{power}}}"

        sign = "-" if rounded < 0 else "+"
        terms.append((sign, body))

    if not terms:
        return "0"

    first_sign, first_body = terms[0]
    expr = f"-{first_body}" if first_sign == "-" else first_body
    for sign, body in terms[1:]:
        expr += f" {sign} {body}"
    return expr


def _build_matrix_latex(system_payload: dict, var: str, decimals: int) -> str:
    shape = system_payload.get("shape", {})
    outputs = int(shape["outputs"])
    inputs = int(shape["inputs"])
    entries = system_payload.get("entries", {})

    rows: list[str] = []
    for i in range(1, outputs + 1):
        row_cells: list[str] = []
        for j in range(1, inputs + 1):
            key = f"y{i}_u{j}"
            if key not in entries:
                raise KeyError(f"Missing transfer entry in JSON: {key}")

            entry = entries[key]
            num = _poly_to_latex(entry["numerator_coeffs"], var, decimals)
            den = _poly_to_latex(entry["denominator_coeffs"], var, decimals)
            row_cells.append(rf"\frac{{{num}}}{{{den}}}")
        rows.append(" & ".join(row_cells))

    matrix_body = r" \\" + "\n"
    matrix_body = matrix_body.join(rows)
    return "\\begin{bmatrix}\n" + matrix_body + "\n\\end{bmatrix}"


def main() -> None:
    args = _parse_args()
    coeff_json_path = _resolve_coeff_json(args)

    with coeff_json_path.open("r", encoding="utf-8") as f:
        payload = json.load(f)

    var = str(payload.get("variable", "s"))
    true_payload = payload["true"]
    est_payload = payload["est"]

    true_matrix = _build_matrix_latex(true_payload, var, args.decimals)
    est_matrix = _build_matrix_latex(est_payload, var, args.decimals)

    latex_lines = [
        "% Auto-generated by visualize_transfer_function.py",
        f"% Source: {coeff_json_path}",
        f"% Rounded to {int(args.decimals)} decimals",
        "",
        rf"\[ G_{{\mathrm{{true}}}}({var}) =",
        true_matrix,
        r"\]",
        "",
        rf"\[ G_{{\mathrm{{est}}}}({var}) =",
        est_matrix,
        r"\]",
        "",
    ]
    latex_text = "\n".join(latex_lines)

    if args.output_tex is not None:
        out_path = args.output_tex.expanduser()
    else:
        out_path = coeff_json_path.parent / "transfer_function_matrix_latex.tex"

    out_path.write_text(latex_text, encoding="utf-8")
    print(f"Saved LaTeX transfer-function matrices to {out_path}")


if __name__ == "__main__":
    main()
